---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: disallow-self-provisioner-placement-rule
  namespace: rhacm-policies
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-disallow-self-provisioner
  kind: Policy
  apiGroup: policy.open-cluster-management.io
